import type { Product } from "@/lib/types";

/* ============================================================================
 * PLACEHOLDER PRICES — NOT REAL PRICING
 *
 * Every `price` below is an invented UZS figure. They exist so the catalog UI
 * has something to render and so currency formatting can be exercised. They
 * must be replaced with real prices before the catalog is shown to customers.
 *
 * Three products keep `price: null` on purpose, to exercise the
 * "price not set" path that shows a contact action instead of a price.
 * ==========================================================================*/
export const products: Product[] = [
  {
    id: "cat-injector-3126",
    slug: "cat-fuel-injector-3126",
    name: { uz: "CAT 3126 yonilg'i forsunkasi", ru: "Топливная форсунка CAT 3126", en: "CAT 3126 Fuel Injector" },
    sku: "DP-INJ-3126",
    oemNumbers: ["127-8213"],
    price: 3450000,
    categoryId: "injector",
    brandId: "cat",
    description: {
      uz: "CAT 3126 seriyali dvigatellar uchun OEM sifatidagi yonilg'i forsunkasi.",
      ru: "Топливная форсунка OEM-качества для двигателей серии CAT 3126.",
      en: "OEM-quality fuel injector for CAT 3126 series engines.",
    },
    compatibleModels: ["CAT 320D", "CAT 325D", "CAT 330D"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Materiali", ru: "Материал", en: "Material" }, value: "Steel alloy" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Side", "Package"],
  },
  {
    id: "komatsu-turbo-pc200",
    slug: "komatsu-turbocharger-pc200-8",
    name: { uz: "Komatsu PC200-8 turbokompressori", ru: "Турбокомпрессор Komatsu PC200-8", en: "Komatsu PC200-8 Turbocharger" },
    sku: "DP-TRB-PC200",
    oemNumbers: ["6754-81-8097"],
    price: 18900000,
    categoryId: "turbocharger",
    brandId: "komatsu",
    description: {
      uz: "Komatsu PC200-8 ekskavatorlari uchun ishonchli turbokompressor.",
      ru: "Надёжный турбокомпрессор для экскаваторов Komatsu PC200-8.",
      en: "Reliable turbocharger for Komatsu PC200-8 excavators.",
    },
    compatibleModels: ["Komatsu PC200-8", "Komatsu PC220-8"],
    stockStatus: "limited",
    specs: [
      { label: { uz: "Tur", ru: "Тип", en: "Type" }, value: "Wastegate" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "6 months" },
    ],
    imageLabels: ["Front", "Side"],
  },
  {
    id: "volvo-hyp-ec210",
    slug: "volvo-hydraulic-pump-ec210",
    name: { uz: "Volvo EC210 gidravlik nasosi", ru: "Гидравлический насос Volvo EC210", en: "Volvo EC210 Hydraulic Pump" },
    sku: "DP-HYP-EC210",
    oemNumbers: ["VOE14514151"],
    price: 27500000,
    categoryId: "hydraulic-pump",
    brandId: "volvo",
    description: {
      uz: "Volvo EC210 ekskavatorlari uchun asosiy gidravlik nasos.",
      ru: "Основной гидравлический насос для экскаваторов Volvo EC210.",
      en: "Main hydraulic pump for Volvo EC210 excavators.",
    },
    compatibleModels: ["Volvo EC210B", "Volvo EC210C"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Bosim", ru: "Давление", en: "Pressure" }, value: "350 bar" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Side", "Package"],
  },
  {
    id: "hitachi-piston-zx330",
    slug: "hitachi-piston-kit-zx330",
    name: { uz: "Hitachi ZX330 porshen to'plami", ru: "Комплект поршней Hitachi ZX330", en: "Hitachi ZX330 Piston Kit" },
    sku: "DP-PST-ZX330",
    oemNumbers: ["4306413"],
    price: 6200000,
    categoryId: "piston",
    brandId: "hitachi",
    description: {
      uz: "Hitachi ZX330 dvigatellari uchun to'liq porshen to'plami.",
      ru: "Полный комплект поршней для двигателей Hitachi ZX330.",
      en: "Complete piston kit for Hitachi ZX330 engines.",
    },
    compatibleModels: ["Hitachi ZX330", "Hitachi ZX350"],
    stockStatus: "out_of_stock",
    specs: [
      { label: { uz: "Diametri", ru: "Диаметр", en: "Diameter" }, value: "108 mm" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "6 months" },
    ],
    imageLabels: ["Front", "Package"],
  },
  {
    id: "jcb-engine-3cx",
    slug: "jcb-engine-gasket-set-3cx",
    name: { uz: "JCB 3CX dvigatel prokladkalari to'plami", ru: "Комплект прокладок двигателя JCB 3CX", en: "JCB 3CX Engine Gasket Set" },
    sku: "DP-ENG-3CX",
    oemNumbers: ["320/09501"],
    price: null,
    categoryId: "engine-parts",
    brandId: "jcb",
    description: {
      uz: "JCB 3CX ekskavator-yuklagichlar uchun to'liq prokladkalar to'plami.",
      ru: "Полный комплект прокладок для экскаваторов-погрузчиков JCB 3CX.",
      en: "Full gasket set for JCB 3CX backhoe loaders.",
    },
    compatibleModels: ["JCB 3CX", "JCB 4CX"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Material", ru: "Материал", en: "Material" }, value: "Reinforced composite" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Package"],
  },
  {
    id: "hyundai-track-r210",
    slug: "hyundai-track-chain-r210",
    name: { uz: "Hyundai R210 gusenitsa zanjiri", ru: "Гусеничная цепь Hyundai R210", en: "Hyundai R210 Track Chain" },
    sku: "DP-TRC-R210",
    oemNumbers: ["81N6-15030"],
    price: 14300000,
    categoryId: "track-chain",
    brandId: "hyundai",
    description: {
      uz: "Hyundai R210 ekskavatorlari uchun bardoshli gusenitsa zanjiri.",
      ru: "Прочная гусеничная цепь для экскаваторов Hyundai R210.",
      en: "Heavy-duty track chain for Hyundai R210 excavators.",
    },
    compatibleModels: ["Hyundai R210", "Hyundai R220"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Bo'g'inlar soni", ru: "Количество звеньев", en: "Link Count" }, value: "45" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Side"],
  },
  {
    id: "doosan-seal-dx225",
    slug: "doosan-seal-kit-dx225",
    name: { uz: "Doosan DX225 zichlagich to'plami", ru: "Комплект уплотнений Doosan DX225", en: "Doosan DX225 Seal Kit" },
    sku: "DP-SEL-DX225",
    oemNumbers: ["2454-1030A"],
    price: 890000,
    categoryId: "seal-kit",
    brandId: "doosan",
    description: {
      uz: "Doosan DX225 gidravlik silindrlari uchun zichlagich to'plami.",
      ru: "Комплект уплотнений для гидроцилиндров Doosan DX225.",
      en: "Seal kit for Doosan DX225 hydraulic cylinders.",
    },
    compatibleModels: ["Doosan DX225", "Doosan DX235"],
    stockStatus: "limited",
    specs: [
      { label: { uz: "Material", ru: "Материал", en: "Material" }, value: "Polyurethane" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "6 months" },
    ],
    imageLabels: ["Front", "Package"],
  },
  {
    id: "cat-turbo-c15",
    slug: "cat-turbocharger-c15",
    name: { uz: "CAT C15 turbokompressori", ru: "Турбокомпрессор CAT C15", en: "CAT C15 Turbocharger" },
    sku: "DP-TRB-C15",
    oemNumbers: ["179-9210"],
    price: 22100000,
    categoryId: "turbocharger",
    brandId: "cat",
    description: {
      uz: "CAT C15 dvigatellari uchun yuqori samarali turbokompressor.",
      ru: "Высокоэффективный турбокомпрессор для двигателей CAT C15.",
      en: "High-performance turbocharger for CAT C15 engines.",
    },
    compatibleModels: ["CAT C15", "CAT C13"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Tur", ru: "Тип", en: "Type" }, value: "Variable geometry" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Side", "Package"],
  },
  {
    id: "komatsu-injector-pc300",
    slug: "komatsu-fuel-injector-pc300",
    name: { uz: "Komatsu PC300 yonilg'i forsunkasi", ru: "Топливная форсунка Komatsu PC300", en: "Komatsu PC300 Fuel Injector" },
    sku: "DP-INJ-PC300",
    oemNumbers: ["6156-11-3300"],
    price: 4150000,
    categoryId: "injector",
    brandId: "komatsu",
    description: {
      uz: "Komatsu PC300 ekskavatorlari uchun yonilg'i forsunkasi.",
      ru: "Топливная форсунка для экскаваторов Komatsu PC300.",
      en: "Fuel injector for Komatsu PC300 excavators.",
    },
    compatibleModels: ["Komatsu PC300-7", "Komatsu PC300-8"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Materiali", ru: "Материал", en: "Material" }, value: "Steel alloy" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Side"],
  },
  {
    id: "volvo-valve-l120",
    slug: "volvo-transmission-valve-l120",
    name: { uz: "Volvo L120 transmissiya klapani", ru: "Клапан трансмиссии Volvo L120", en: "Volvo L120 Transmission Valve" },
    sku: "DP-VLV-L120",
    oemNumbers: ["VOE11192370"],
    price: 1750000,
    categoryId: "valve",
    brandId: "volvo",
    description: {
      uz: "Volvo L120 yuklagichlari uchun transmissiya boshqaruv klapani.",
      ru: "Клапан управления трансмиссией для погрузчиков Volvo L120.",
      en: "Transmission control valve for Volvo L120 loaders.",
    },
    compatibleModels: ["Volvo L120E", "Volvo L120F"],
    stockStatus: "limited",
    specs: [
      { label: { uz: "Tur", ru: "Тип", en: "Type" }, value: "Solenoid" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "6 months" },
    ],
    imageLabels: ["Front", "Package"],
  },
  {
    id: "hitachi-hyp-ex200",
    slug: "hitachi-hydraulic-pump-ex200",
    name: { uz: "Hitachi EX200 gidravlik nasosi", ru: "Гидравлический насос Hitachi EX200", en: "Hitachi EX200 Hydraulic Pump" },
    sku: "DP-HYP-EX200",
    oemNumbers: ["9148983"],
    price: null,
    categoryId: "hydraulic-pump",
    brandId: "hitachi",
    description: {
      uz: "Hitachi EX200 ekskavatorlari uchun asosiy gidravlik nasos.",
      ru: "Основной гидравлический насос для экскаваторов Hitachi EX200.",
      en: "Main hydraulic pump for Hitachi EX200 excavators.",
    },
    compatibleModels: ["Hitachi EX200-3", "Hitachi EX200-5"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Bosim", ru: "Давление", en: "Pressure" }, value: "320 bar" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Side", "Package"],
  },
  {
    id: "jcb-undercarriage-js220",
    slug: "jcb-undercarriage-roller-js220",
    name: { uz: "JCB JS220 yurish g'ildiragi", ru: "Ходовой каток JCB JS220", en: "JCB JS220 Undercarriage Roller" },
    sku: "DP-UNC-JS220",
    oemNumbers: ["333/G6154"],
    price: 31800000,
    categoryId: "undercarriage",
    brandId: "jcb",
    description: {
      uz: "JCB JS220 ekskavatorlari uchun yurish qismi g'ildiragi.",
      ru: "Ходовой каток для экскаваторов JCB JS220.",
      en: "Undercarriage roller for JCB JS220 excavators.",
    },
    compatibleModels: ["JCB JS220", "JCB JS210"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Og'irligi", ru: "Вес", en: "Weight" }, value: "38 kg" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Side"],
  },
  {
    id: "hyundai-piston-r220",
    slug: "hyundai-piston-ring-r220",
    name: { uz: "Hyundai R220 porshen halqasi", ru: "Поршневое кольцо Hyundai R220", en: "Hyundai R220 Piston Ring" },
    sku: "DP-PSR-R220",
    oemNumbers: ["21N6-32020"],
    price: 5600000,
    categoryId: "piston",
    brandId: "hyundai",
    description: {
      uz: "Hyundai R220 dvigatellari uchun porshen halqalari to'plami.",
      ru: "Комплект поршневых колец для двигателей Hyundai R220.",
      en: "Piston ring set for Hyundai R220 engines.",
    },
    compatibleModels: ["Hyundai R220", "Hyundai R210"],
    stockStatus: "out_of_stock",
    specs: [
      { label: { uz: "Diametri", ru: "Диаметр", en: "Diameter" }, value: "102 mm" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "6 months" },
    ],
    imageLabels: ["Front", "Package"],
  },
  {
    id: "doosan-valve-dx140",
    slug: "doosan-engine-valve-dx140",
    name: { uz: "Doosan DX140 dvigatel klapani", ru: "Клапан двигателя Doosan DX140", en: "Doosan DX140 Engine Valve" },
    sku: "DP-ENV-DX140",
    oemNumbers: ["65.02601-6019A"],
    price: 1320000,
    categoryId: "valve",
    brandId: "doosan",
    description: {
      uz: "Doosan DX140 dvigatellari uchun kirish/chiqish klapani.",
      ru: "Впускной/выпускной клапан для двигателей Doosan DX140.",
      en: "Intake/exhaust valve for Doosan DX140 engines.",
    },
    compatibleModels: ["Doosan DX140", "Doosan DX160"],
    stockStatus: "available",
    specs: [
      { label: { uz: "Materiali", ru: "Материал", en: "Material" }, value: "Chrome-plated steel" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "12 months" },
    ],
    imageLabels: ["Front", "Package"],
  },
  {
    id: "cat-transmission-950",
    slug: "cat-transmission-filter-950",
    name: { uz: "CAT 950 transmissiya filtri", ru: "Фильтр трансмиссии CAT 950", en: "CAT 950 Transmission Filter" },
    sku: "DP-TRF-950",
    oemNumbers: ["132-9863"],
    price: null,
    categoryId: "transmission",
    brandId: "cat",
    description: {
      uz: "CAT 950 yuklagichlari uchun transmissiya moyi filtri.",
      ru: "Фильтр трансмиссионного масла для погрузчиков CAT 950.",
      en: "Transmission oil filter for CAT 950 loaders.",
    },
    compatibleModels: ["CAT 950G", "CAT 950H"],
    stockStatus: "limited",
    specs: [
      { label: { uz: "Filtrlash darajasi", ru: "Степень фильтрации", en: "Filtration Rating" }, value: "10 microns" },
      { label: { uz: "Kafolat", ru: "Гарантия", en: "Warranty" }, value: "6 months" },
    ],
    imageLabels: ["Front", "Package"],
  },
];
